 /**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "main.h"
#include "scheduler.h"
#include "tasks.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//semihosting init fcn
extern void initialise_monitor_handles(void);

void error_hanlder(void);

void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);

uint32_t scheduler_stack[OS_SCHEDULER_STACK_WORDS] __attribute__((aligned(8)));

uint32_t task1_stack[1024] __attribute__((aligned(8)));
uint32_t task2_stack[1024] __attribute__((aligned(8)));
uint32_t task3_stack[1024] __attribute__((aligned(8)));
uint32_t task4_stack[1024] __attribute__((aligned(8)));

int main(void)
{
 	os_enable_processor_faults();

	uint32_t scheduler_stack_top = (uint32_t)(scheduler_stack + sizeof(scheduler_stack) / sizeof(scheduler_stack[0]));
	os_init_scheduler_stack(scheduler_stack_top);

	if (os_task_create(task1_handler, 2, task1_stack, sizeof(task1_stack)) != OS_OK) error_hanlder();
	if (os_task_create(task2_handler, 2, task2_stack, sizeof(task2_stack)) != OS_OK) error_hanlder();
	if (os_task_create(task3_handler, 1, task3_stack, sizeof(task3_stack)) != OS_OK) error_hanlder();
	if (os_task_create(task4_handler, 2, task4_stack, sizeof(task4_stack)) != OS_OK) error_hanlder();

	os_init();

	printf("Task schedular initialized\n");

	os_init_systick_timer(TICK_HZ);

	os_switch_to_psp();

	os_task_start();

    /* Loop forever */
	for(;;);
}

void task1_handler(void)
{
	//the tasks never returns(finishes)
	while(1)
	{
		printf("This is task 1\n");
		os_task_delay(5);
	}
}
void task2_handler(void)
{
	while(1)
	{
		printf("This is task 2 \n");
		os_task_delay(4);

	}
}
void task3_handler(void)
{
	while(1)
	{
		printf("This is task 3\n");
		os_task_delay(500);

	}
}
void task4_handler(void)
{
	while(1)
	{
		printf("This is task 4\n");
		os_task_delay(2000);
	}
}

void error_hanlder(void)
{
	while(1);
}


