 /**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "main.h"
#include "scheduler.h"
#include "tasks.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//semihosting init fcn
extern void initialise_monitor_handles(void);

int main(void)
{
 	enable_processor_faults();

	init_scheduler_stack(SCHEDULER_STACK_START);

	init_task_stack();

	initialise_monitor_handles();

	printf("Task schedular\n");

	init_systick_timer(TICK_HZ);

	switch_to_psp();

	task_start();
	
    /* Loop forever */
	for(;;);
}

void idle_task(void)
{
	while(1);
}

void task1_handler(void)
{
	//the tasks never returns(finishes)
	while(1)
	{
		printf("This is task 1\n");
		task_delay(1000);
	}
}
void task2_handler(void)
{
	while(1)
	{
		printf("This is task 2 \n");
		task_delay(500);

	}
}
void task3_handler(void)
{
	while(1)
	{
		printf("This is task 3\n");
		task_delay(250);

	}
}
void task4_handler(void)
{
	while(1)
	{
		printf("This is task 4\n");
		task_delay(2000);
	}
}


